version: '3'
services:
  node:
    container_name: nodejs
    image: node
    hostname: localhost
    build: .
    restart: always
    ports:
      - "5001:8080"
      - "5002:8080"
    links:
     - db
  db:
    container_name: mongo
    image: mongo
    hostname: mongo
    ports:
      - "27020:27017"
  web:
    container_name: nginx
    image: nginx
    hostname: nginx
    ports:
      - "3000:80"
